#!/bin/bash

if [[ $OSTYPE == darwin* ]]; then
    current_dir=$(dirname $0)
    current_path=$PWD${current_dir:1}
else
    current_path=$(dirname $(readlink -f $0))
fi

ln -s "$current_path"/.vimrc ~/.vimrc
ln -s "$current_path"/.vim ~/.vim
